apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/magicalartist-maker/cicd.git
    targetRevision: main
    path: argocd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
